### ISSUE TITLE
Fix BepInEx Assembly Reference

### ISSUE THREAD

**Issue by microsoftv** [PassivePicasso/Rain-of-Stages#10]
Change HintPath from:
`<HintPath>$(RoR2Path)BepInEx\core\BepInEx.dll</HintPath>`
to:
`<HintPath>$(RoR2Path)\BepInEx\core\BepInEx.dll</HintPath>`
This fix is meant for when #8 is in effect.

**Comment by PassivePicasso** [comment]
this reconfiguration has too much potential to cause unexpected behaviour
