### ISSUE TITLE
Optimize RoR2Path

### ISSUE THREAD

**Issue by microsoftv** [PassivePicasso/Rain-of-Stages#8]
Change the RoR2Path in the RainOfStages project to `<RoR2Path>..\..\..\..</RoR2Path>`. 
This will allow users to drag and drop the Rain-of-Stages repository directly into BepInEx/plugins with no issues regarding assemblies (besides the RainOfStages.Shared assembly).

**Comment by PassivePicasso** [comment]
this reconfiguration has too much potential to cause unexpected behaviour
