### ISSUE TITLE
Fix HintPath for R2API Assembly Reference

### ISSUE THREAD

**Issue by microsoftv** [PassivePicasso/Rain-of-Stages#9]
Change the HintPath for the R2API Assembly Reference from:
`<HintPath>..\..\Risk of Rain 2\BepInEx\plugins\R2API\R2API.dll</HintPath>`
to:
`<HintPath>$(RoR2Path)\BepInEx\plugins\R2API\R2API.dll</HintPath>`
This fix assumes #8 is in effect.

**Comment by PassivePicasso** [comment]
this reconfiguration has too much potential to cause unexpected behaviour
